# Source: postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: "default"
  labels:
    app.kubernetes.io/instance: {{ include "postgresql.fullname" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.0.0
    helm.sh/chart: postgresql-16.0.1
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: {{ include "postgresql.fullname" . }}
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary