apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-app-clearsessions
  namespace: default
spec:
  schedule: "0 0 * * 6-7"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
            - name: clearsessions-container
              image: django_app
              command: ['python', 'manage.py', 'clearsessions']
              imagePullPolicy: Never
              envFrom:
                - secretRef:
                    name: dj-secret
          restartPolicy: Never
      backoffLimit: 3