apiVersion: v1
kind: Pod
metadata:
  namespace: edu-happy-goldberg
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: edu-happy-goldberg
status:
  loadBalancer: {}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30231
  selector:
    app: nginx
  type: NodePort
  sessionAffinity: None
