# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: "default"
  labels:
    app.kubernetes.io/instance: {{ include "postgresql.fullname" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.0.0
    helm.sh/chart: postgresql-16.0.1
type: Opaque
data:
  postgres-password: "M2JZZWZVa0JGaQ=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords