# Source: postgresql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: "default"
  labels:
    app.kubernetes.io/instance: {{ include "postgresql.fullname" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.0.0
    helm.sh/chart: postgresql-16.0.1
automountServiceAccountToken: false